zinc-coating-v0:
  policy: 'MlpPolicy'
  n_timesteps: !!float 1e7
  learning_rate: lin_2.5e-4
  batch_size: 64
  train_freq: 64
  gradient_steps: 4
  target_update_interval: 2
  buffer_size: 500000
  learning_starts: 5000