zinc-coating-v0:
  policy: 'MlpPolicy'
  n_timesteps: !!float 1e7
  learning_rate: lin_2.5e-4
  train_freq: 64
  gradient_steps: 2
  buffer_size: 1000000
  learning_starts: 5000
  # log: 'log_continuous'