zinc-coating-v0:
  policy: 'MlpPolicy'
  n_timesteps: !!float 2e6
  learning_rate: lin_2.5e-4
  batch_size: 256
  train_freq: 64
  tau: 0.02
  gradient_steps: 4
  target_update_interval: 4
  buffer_size: 500000
  learning_starts: 5000