zinc-coating-v0:
  policy: 'MlpPolicy'
  n_timesteps: !!float 3e6
  learning_rate: lin_2.5e-4
  batch_size: 64
  train_freq: 1
  tau: 0.01
  gradient_steps: 1
  target_update_interval: 1
  buffer_size: 500000
  learning_starts: 5000
  kl_mean_constraint: 0.01